import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.woff",
  variable: "--Roboto-Regular",
  weight: "100 900",
});
const robotoBlod = localFont({
  src: "./fonts/Roboto-Bold.woff",
  variable: "--Roboto-Blod",
  weight: "100 900",
});
const robotoMedium = localFont({
  src: "./fonts/Roboto-Medium.woff",
  variable: "--Roboto-Medium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoRegular.variable} ${robotoBlod.variable}  ${robotoMedium.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
